version: '3.7'
services:
    mongodb_container:
        # This image automatically creates a replica set required for transactions
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: prisma
            INIT_WAIT_SEC: 3
        ports:
            - 27017:27017
    redis:
        image: 'redis:alpine'

        command: redis-server --requirepass sOmE_sEcUrE_pAsS

        ports:
            - '6379:6379'

        volumes:
            - $PWD/redis-data:/var/lib/redis
              - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

        environment:
            - REDIS_REPLICATION_MODE=master

        networks:
            node_net:
                ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
    node_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
